services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - C:\minio\data:/data
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    restart: always

volumes:
  D:\minio\data: